/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Career = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const NewsArticle = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Int,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Ship = IDL.Record({
  'shipType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCareers' : IDL.Func([], [IDL.Vec(Career)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllShips' : IDL.Func([], [IDL.Vec(Ship)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Career = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const NewsArticle = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Int,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Ship = IDL.Record({
    'shipType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCareers' : IDL.Func([], [IDL.Vec(Career)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllShips' : IDL.Func([], [IDL.Vec(Ship)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };